#3) Crie um programa que leia o nome e o salário de um funcionário, mostrando no
#   final uma mensagem.

print("#####################################")
print("# confirmação da folha de pagamento #")
print("#####################################")

nome = input("qual seu nome: ")
salario = input ("quanto você recebeu: ")

print("vamos confirmar", nome,"você recebeu", salario, "neste mês. Correto?")
