
## CRIE UM PROGRAMA QUE LEIA O NOME COMPLETO DE UMA PESSOA
## MOSTRE-O COM TODAS AS LETRAS MAIUSCULAS
## MOSTRE-O COM TODAS AS LETRAS MINUSCULAS
## MOSTRE QUANTAS LETRAS SEM CONSIDERA OS ESPAÇOES
